from sqlalchemy import Column, Integer, String

from .base import Base

class OrigemLancamento(Base):
    """
    Lookup table for origin types of financial entries (lancamentos).
    
    This table stores the different types of origins for entries:
    - Manual: Manually entered by a user
    - Automático: Automatically generated by system routines or DW
    - Importado: Imported from spreadsheet or external integration
    
    The ind_status field allows origins to be deactivated without deletion,
    maintaining referential integrity while controlling available options.
    """
    __tablename__ = 'flc_origem_lancamento'
    cod_origem_lancamento = Column(Integer, primary_key=True)
    dsc_origem_lancamento = Column(String(50), nullable=False)
    ind_status = Column(String(1), default='A', nullable=False)  # 'A' = Ativo, 'I' = Inativo
