"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-07-11 22:11:28.979418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flc_conferencia',
    sa.Column('dat_conferencia', sa.Date(), nullable=False),
    sa.Column('val_saldo_anterior', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('val_liberacoes', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('val_conf_liberacoes', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('val_soma_anter_liberacoes', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('val_pagamentos', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('val_conf_pagamentos', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('val_saldo_final', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('dat_conferencia', name=op.f('pk_flc_conferencia'))
    )
    op.create_table('flc_conta_bancaria',
    sa.Column('seq_conta', sa.Integer(), nullable=False),
    sa.Column('cod_banco', sa.String(length=10), nullable=False),
    sa.Column('num_agencia', sa.String(length=20), nullable=False),
    sa.Column('num_conta', sa.String(length=30), nullable=False),
    sa.Column('dsc_conta', sa.String(length=100), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_cadastro', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('seq_conta', name=op.f('pk_flc_conta_bancaria'))
    )
    op.create_table('flc_orgao',
    sa.Column('cod_orgao', sa.Integer(), nullable=False),
    sa.Column('nom_orgao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cod_orgao', name=op.f('pk_flc_orgao'))
    )
    op.create_table('flc_origem_lancamento',
    sa.Column('cod_origem_lancamento', sa.Integer(), nullable=False),
    sa.Column('dsc_origem_lancamento', sa.String(length=50), nullable=False),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('cod_origem_lancamento', name=op.f('pk_flc_origem_lancamento'))
    )
    op.create_table('flc_parametro_global',
    sa.Column('seq_parametro_global', sa.Integer(), nullable=False),
    sa.Column('nom_parametro', sa.String(length=50), nullable=False),
    sa.Column('dsc_parametro', sa.String(length=255), nullable=True),
    sa.Column('cod_tipo', sa.String(length=1), nullable=False),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('seq_parametro_global', name=op.f('pk_flc_parametro_global')),
    sa.UniqueConstraint('nom_parametro', name=op.f('uq_flc_parametro_global_nom_parametro'))
    )
    op.create_table('flc_qualificador',
    sa.Column('seq_qualificador', sa.Integer(), nullable=False),
    sa.Column('num_qualificador', sa.String(length=20), nullable=False),
    sa.Column('dsc_qualificador', sa.String(length=255), nullable=False),
    sa.Column('cod_qualificador_pai', sa.Integer(), nullable=True),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['cod_qualificador_pai'], ['flc_qualificador.seq_qualificador'], name=op.f('fk_flc_qualificador_cod_qualificador_pai_flc_qualificador')),
    sa.PrimaryKeyConstraint('seq_qualificador', name=op.f('pk_flc_qualificador')),
    sa.UniqueConstraint('num_qualificador', name=op.f('uq_flc_qualificador_num_qualificador'))
    )
    op.create_table('flc_simulador_cenario',
    sa.Column('seq_simulador_cenario', sa.Integer(), nullable=False),
    sa.Column('nom_cenario', sa.String(length=100), nullable=False),
    sa.Column('dsc_cenario', sa.String(length=255), nullable=True),
    sa.Column('ano_base', sa.Integer(), nullable=False),
    sa.Column('meses_projecao', sa.Integer(), nullable=False),
    sa.Column('cod_periodicidade', sa.String(length=15), nullable=False),
    sa.Column('cod_metodo_base', sa.String(length=20), nullable=False),
    sa.Column('json_config_base', sa.Text(), nullable=True),
    sa.Column('dat_criacao', sa.Date(), nullable=False),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=False),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seq_simulador_cenario', name=op.f('pk_flc_simulador_cenario'))
    )
    op.create_table('flc_tipo_lancamento',
    sa.Column('cod_tipo_lancamento', sa.Integer(), nullable=False),
    sa.Column('dsc_tipo_lancamento', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('cod_tipo_lancamento', name=op.f('pk_flc_tipo_lancamento'))
    )
    op.create_table('flc_alerta',
    sa.Column('seq_alerta', sa.Integer(), nullable=False),
    sa.Column('nom_alerta', sa.String(length=255), nullable=False),
    sa.Column('metric', sa.String(length=20), nullable=False),
    sa.Column('seq_qualificador', sa.Integer(), nullable=True),
    sa.Column('logic', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('emails', sa.String(length=255), nullable=True),
    sa.Column('notif_system', sa.String(length=1), nullable=True),
    sa.Column('notif_email', sa.String(length=1), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=False),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seq_qualificador'], ['flc_qualificador.seq_qualificador'], name=op.f('fk_flc_alerta_seq_qualificador_flc_qualificador')),
    sa.PrimaryKeyConstraint('seq_alerta', name=op.f('pk_flc_alerta'))
    )
    op.create_table('flc_cenario_despesa',
    sa.Column('seq_cenario_despesa', sa.Integer(), nullable=False),
    sa.Column('seq_simulador_cenario', sa.Integer(), nullable=False),
    sa.Column('cod_tipo_cenario', sa.String(length=20), nullable=False),
    sa.Column('json_configuracao', sa.Text(), nullable=True),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['seq_simulador_cenario'], ['flc_simulador_cenario.seq_simulador_cenario'], name=op.f('fk_flc_cenario_despesa_seq_simulador_cenario_flc_simulador_cenario')),
    sa.PrimaryKeyConstraint('seq_cenario_despesa', name=op.f('pk_flc_cenario_despesa')),
    sa.UniqueConstraint('seq_simulador_cenario', name=op.f('uq_flc_cenario_despesa_seq_simulador_cenario'))
    )
    op.create_table('flc_cenario_parametro_valor',
    sa.Column('seq_cenario_parametro_valor', sa.Integer(), nullable=False),
    sa.Column('seq_simulador_cenario', sa.Integer(), nullable=False),
    sa.Column('nom_parametro', sa.String(length=50), nullable=False),
    sa.Column('val_parametro', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['seq_simulador_cenario'], ['flc_simulador_cenario.seq_simulador_cenario'], name=op.f('fk_flc_cenario_parametro_valor_seq_simulador_cenario_flc_simulador_cenario')),
    sa.PrimaryKeyConstraint('seq_cenario_parametro_valor', name=op.f('pk_flc_cenario_parametro_valor')),
    sa.UniqueConstraint('seq_simulador_cenario', 'nom_parametro', name='uix_cenario_param_nome')
    )
    op.create_table('flc_cenario_receita',
    sa.Column('seq_cenario_receita', sa.Integer(), nullable=False),
    sa.Column('seq_simulador_cenario', sa.Integer(), nullable=False),
    sa.Column('cod_tipo_cenario', sa.String(length=20), nullable=False),
    sa.Column('json_configuracao', sa.Text(), nullable=True),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['seq_simulador_cenario'], ['flc_simulador_cenario.seq_simulador_cenario'], name=op.f('fk_flc_cenario_receita_seq_simulador_cenario_flc_simulador_cenario')),
    sa.PrimaryKeyConstraint('seq_cenario_receita', name=op.f('pk_flc_cenario_receita')),
    sa.UniqueConstraint('seq_simulador_cenario', name=op.f('uq_flc_cenario_receita_seq_simulador_cenario'))
    )
    op.create_table('flc_lancamento',
    sa.Column('seq_lancamento', sa.Integer(), nullable=False),
    sa.Column('dat_lancamento', sa.Date(), nullable=False),
    sa.Column('seq_qualificador', sa.Integer(), nullable=False),
    sa.Column('val_lancamento', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cod_tipo_lancamento', sa.Integer(), nullable=False),
    sa.Column('cod_origem_lancamento', sa.Integer(), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=False),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('seq_conta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cod_origem_lancamento'], ['flc_origem_lancamento.cod_origem_lancamento'], name=op.f('fk_flc_lancamento_cod_origem_lancamento_flc_origem_lancamento')),
    sa.ForeignKeyConstraint(['cod_tipo_lancamento'], ['flc_tipo_lancamento.cod_tipo_lancamento'], name=op.f('fk_flc_lancamento_cod_tipo_lancamento_flc_tipo_lancamento')),
    sa.ForeignKeyConstraint(['seq_conta'], ['flc_conta_bancaria.seq_conta'], name=op.f('fk_flc_lancamento_seq_conta_flc_conta_bancaria')),
    sa.ForeignKeyConstraint(['seq_qualificador'], ['flc_qualificador.seq_qualificador'], name=op.f('fk_flc_lancamento_seq_qualificador_flc_qualificador')),
    sa.PrimaryKeyConstraint('seq_lancamento', name=op.f('pk_flc_lancamento'))
    )
    op.create_table('flc_loa',
    sa.Column('seq_loa', sa.Integer(), nullable=False),
    sa.Column('num_ano', sa.Integer(), nullable=False),
    sa.Column('seq_qualificador', sa.Integer(), nullable=False),
    sa.Column('val_loa', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['seq_qualificador'], ['flc_qualificador.seq_qualificador'], name=op.f('fk_flc_loa_seq_qualificador_flc_qualificador')),
    sa.PrimaryKeyConstraint('seq_loa', name=op.f('pk_flc_loa'))
    )
    op.create_table('flc_mapeamento',
    sa.Column('seq_mapeamento', sa.Integer(), nullable=False),
    sa.Column('seq_qualificador', sa.Integer(), nullable=False),
    sa.Column('dsc_mapeamento', sa.String(length=255), nullable=False),
    sa.Column('txt_condicao', sa.String(length=500), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['seq_qualificador'], ['flc_qualificador.seq_qualificador'], name=op.f('fk_flc_mapeamento_seq_qualificador_flc_qualificador')),
    sa.PrimaryKeyConstraint('seq_mapeamento', name=op.f('pk_flc_mapeamento'))
    )
    op.create_table('flc_pagamento',
    sa.Column('seq_pagamento', sa.Integer(), nullable=False),
    sa.Column('dat_pagamento', sa.Date(), nullable=False),
    sa.Column('cod_orgao', sa.Integer(), nullable=False),
    sa.Column('seq_qualificador', sa.Integer(), nullable=True),
    sa.Column('val_pagamento', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('dsc_pagamento', sa.String(length=255), nullable=True),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['cod_orgao'], ['flc_orgao.cod_orgao'], name=op.f('fk_flc_pagamento_cod_orgao_flc_orgao')),
    sa.ForeignKeyConstraint(['seq_qualificador'], ['flc_qualificador.seq_qualificador'], name=op.f('fk_flc_pagamento_seq_qualificador_flc_qualificador')),
    sa.PrimaryKeyConstraint('seq_pagamento', name=op.f('pk_flc_pagamento'))
    )
    op.create_table('flc_projecao_versao',
    sa.Column('seq_projecao_versao', sa.Integer(), nullable=False),
    sa.Column('seq_simulador_cenario', sa.Integer(), nullable=False),
    sa.Column('nom_versao', sa.String(length=80), nullable=False),
    sa.Column('dsc_motivo', sa.String(length=255), nullable=True),
    sa.Column('dat_versao', sa.DateTime(), nullable=False),
    sa.Column('cod_pessoa', sa.Integer(), nullable=True),
    sa.Column('ind_publicado', sa.String(length=1), nullable=False),
    sa.Column('json_inputs', sa.Text(), nullable=True),
    sa.Column('json_resumo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['seq_simulador_cenario'], ['flc_simulador_cenario.seq_simulador_cenario'], name=op.f('fk_flc_projecao_versao_seq_simulador_cenario_flc_simulador_cenario')),
    sa.PrimaryKeyConstraint('seq_projecao_versao', name=op.f('pk_flc_projecao_versao'))
    )
    op.create_table('flc_rubrica_formula',
    sa.Column('seq_rubrica_formula', sa.Integer(), nullable=False),
    sa.Column('seq_qualificador', sa.Integer(), nullable=False),
    sa.Column('nom_formula', sa.String(length=100), nullable=False),
    sa.Column('dsc_formula_expressao', sa.Text(), nullable=False),
    sa.Column('cod_metodo_base', sa.String(length=20), nullable=False),
    sa.Column('json_config_base', sa.Text(), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['seq_qualificador'], ['flc_qualificador.seq_qualificador'], name=op.f('fk_flc_rubrica_formula_seq_qualificador_flc_qualificador')),
    sa.PrimaryKeyConstraint('seq_rubrica_formula', name=op.f('pk_flc_rubrica_formula')),
    sa.UniqueConstraint('seq_qualificador', name=op.f('uq_flc_rubrica_formula_seq_qualificador'))
    )
    op.create_table('flc_saldo_conta',
    sa.Column('seq_saldo_conta', sa.Integer(), nullable=False),
    sa.Column('seq_conta', sa.Integer(), nullable=False),
    sa.Column('dat_saldo', sa.Date(), nullable=False),
    sa.Column('val_saldo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=False),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seq_conta'], ['flc_conta_bancaria.seq_conta'], name=op.f('fk_flc_saldo_conta_seq_conta_flc_conta_bancaria')),
    sa.PrimaryKeyConstraint('seq_saldo_conta', name=op.f('pk_flc_saldo_conta')),
    sa.UniqueConstraint('seq_conta', 'dat_saldo', name='uk_saldo_conta_data')
    )
    op.create_table('flc_simulador_cenario_historico',
    sa.Column('seq_historico', sa.Integer(), nullable=False),
    sa.Column('seq_simulador_cenario', sa.Integer(), nullable=False),
    sa.Column('dat_snapshot', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_snapshot', sa.Integer(), nullable=False),
    sa.Column('json_snapshot', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['seq_simulador_cenario'], ['flc_simulador_cenario.seq_simulador_cenario'], name=op.f('fk_flc_simulador_cenario_historico_seq_simulador_cenario_flc_simulador_cenario')),
    sa.PrimaryKeyConstraint('seq_historico', name=op.f('pk_flc_simulador_cenario_historico'))
    )
    op.create_table('flc_alerta_gerado',
    sa.Column('seq_alerta_gerado', sa.Integer(), nullable=False),
    sa.Column('seq_alerta', sa.Integer(), nullable=True),
    sa.Column('dat_processamento', sa.Date(), nullable=True),
    sa.Column('dat_referencia', sa.Date(), nullable=False),
    sa.Column('valor_obtido', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valor_esperado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('severidade', sa.String(length=20), nullable=True),
    sa.Column('ind_lido', sa.String(length=1), nullable=False),
    sa.Column('ind_resolvido', sa.String(length=1), nullable=False),
    sa.Column('dat_leitura', sa.DateTime(), nullable=True),
    sa.Column('dat_resolucao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seq_alerta'], ['flc_alerta.seq_alerta'], name=op.f('fk_flc_alerta_gerado_seq_alerta_flc_alerta')),
    sa.PrimaryKeyConstraint('seq_alerta_gerado', name=op.f('pk_flc_alerta_gerado'))
    )
    op.create_table('flc_cenario_despesa_ajuste',
    sa.Column('seq_cenario_despesa_ajuste', sa.Integer(), nullable=False),
    sa.Column('seq_cenario_despesa', sa.Integer(), nullable=False),
    sa.Column('seq_qualificador', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('cod_tipo_ajuste', sa.String(length=1), nullable=False),
    sa.Column('val_ajuste', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('dsc_ajuste', sa.String(length=100), nullable=True),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['seq_cenario_despesa'], ['flc_cenario_despesa.seq_cenario_despesa'], name=op.f('fk_flc_cenario_despesa_ajuste_seq_cenario_despesa_flc_cenario_despesa')),
    sa.ForeignKeyConstraint(['seq_qualificador'], ['flc_qualificador.seq_qualificador'], name=op.f('fk_flc_cenario_despesa_ajuste_seq_qualificador_flc_qualificador')),
    sa.PrimaryKeyConstraint('seq_cenario_despesa_ajuste', name=op.f('pk_flc_cenario_despesa_ajuste')),
    sa.UniqueConstraint('seq_cenario_despesa', 'seq_qualificador', 'ano', 'mes', name='uix_cenario_despesa_ajuste')
    )
    op.create_table('flc_cenario_receita_ajuste',
    sa.Column('seq_cenario_receita_ajuste', sa.Integer(), nullable=False),
    sa.Column('seq_cenario_receita', sa.Integer(), nullable=False),
    sa.Column('seq_qualificador', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('cod_tipo_ajuste', sa.String(length=1), nullable=False),
    sa.Column('val_ajuste', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('dsc_ajuste', sa.String(length=100), nullable=True),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['seq_cenario_receita'], ['flc_cenario_receita.seq_cenario_receita'], name=op.f('fk_flc_cenario_receita_ajuste_seq_cenario_receita_flc_cenario_receita')),
    sa.ForeignKeyConstraint(['seq_qualificador'], ['flc_qualificador.seq_qualificador'], name=op.f('fk_flc_cenario_receita_ajuste_seq_qualificador_flc_qualificador')),
    sa.PrimaryKeyConstraint('seq_cenario_receita_ajuste', name=op.f('pk_flc_cenario_receita_ajuste')),
    sa.UniqueConstraint('seq_cenario_receita', 'seq_qualificador', 'ano', 'mes', name='uix_cenario_receita_ajuste')
    )
    op.create_table('flc_modelo_economico_parametro',
    sa.Column('seq_parametro', sa.Integer(), nullable=False),
    sa.Column('seq_cenario_receita', sa.Integer(), nullable=False),
    sa.Column('nom_variavel', sa.String(length=50), nullable=False),
    sa.Column('val_coeficiente', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('json_valores_historicos', sa.Text(), nullable=True),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['seq_cenario_receita'], ['flc_cenario_receita.seq_cenario_receita'], name=op.f('fk_flc_modelo_economico_parametro_seq_cenario_receita_flc_cenario_receita')),
    sa.PrimaryKeyConstraint('seq_parametro', name=op.f('pk_flc_modelo_economico_parametro'))
    )
    op.create_table('flc_projecao_valor',
    sa.Column('seq_projecao_valor', sa.Integer(), nullable=False),
    sa.Column('seq_projecao_versao', sa.Integer(), nullable=False),
    sa.Column('seq_qualificador', sa.Integer(), nullable=True),
    sa.Column('cod_tipo', sa.String(length=1), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('val_projetado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('val_realizado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['seq_projecao_versao'], ['flc_projecao_versao.seq_projecao_versao'], name=op.f('fk_flc_projecao_valor_seq_projecao_versao_flc_projecao_versao'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seq_qualificador'], ['flc_qualificador.seq_qualificador'], name=op.f('fk_flc_projecao_valor_seq_qualificador_flc_qualificador')),
    sa.PrimaryKeyConstraint('seq_projecao_valor', name=op.f('pk_flc_projecao_valor'))
    )
    with op.batch_alter_table('flc_projecao_valor', schema=None) as batch_op:
        batch_op.create_index('ix_projecao_valor_tipo', ['cod_tipo'], unique=False)
        batch_op.create_index('ix_projecao_valor_versao_qual_periodo', ['seq_projecao_versao', 'seq_qualificador', 'ano', 'mes'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flc_projecao_valor', schema=None) as batch_op:
        batch_op.drop_index('ix_projecao_valor_versao_qual_periodo')
        batch_op.drop_index('ix_projecao_valor_tipo')

    op.drop_table('flc_projecao_valor')
    op.drop_table('flc_modelo_economico_parametro')
    op.drop_table('flc_cenario_receita_ajuste')
    op.drop_table('flc_cenario_despesa_ajuste')
    op.drop_table('flc_alerta_gerado')
    op.drop_table('flc_simulador_cenario_historico')
    op.drop_table('flc_saldo_conta')
    op.drop_table('flc_rubrica_formula')
    op.drop_table('flc_projecao_versao')
    op.drop_table('flc_pagamento')
    op.drop_table('flc_mapeamento')
    op.drop_table('flc_loa')
    op.drop_table('flc_lancamento')
    op.drop_table('flc_cenario_receita')
    op.drop_table('flc_cenario_parametro_valor')
    op.drop_table('flc_cenario_despesa')
    op.drop_table('flc_alerta')
    op.drop_table('flc_tipo_lancamento')
    op.drop_table('flc_simulador_cenario')
    op.drop_table('flc_qualificador')
    op.drop_table('flc_parametro_global')
    op.drop_table('flc_origem_lancamento')
    op.drop_table('flc_orgao')
    op.drop_table('flc_conta_bancaria')
    op.drop_table('flc_conferencia')
    # ### end Alembic commands ###
