"""cria flc_usuario

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-11 22:42:59.209861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flc_usuario',
    sa.Column('seq_usuario', sa.Integer(), nullable=False),
    sa.Column('nom_usuario', sa.String(length=50), nullable=False),
    sa.Column('nom_completo', sa.String(length=120), nullable=True),
    sa.Column('txt_hash_senha', sa.String(length=60), nullable=False),
    sa.Column('ind_troca_senha', sa.String(length=1), nullable=False),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=True),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seq_usuario', name=op.f('pk_flc_usuario')),
    sa.UniqueConstraint('nom_usuario', name=op.f('uq_flc_usuario_nom_usuario'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flc_usuario')
    # ### end Alembic commands ###
