"""cria tabelas de perfis e permissoes

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-12 09:01:31.113706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flc_perfil',
    sa.Column('seq_perfil', sa.Integer(), nullable=False),
    sa.Column('cod_perfil', sa.String(length=30), nullable=False),
    sa.Column('dsc_perfil', sa.String(length=255), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=True),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seq_perfil', name=op.f('pk_flc_perfil')),
    sa.UniqueConstraint('cod_perfil', name=op.f('uq_flc_perfil_cod_perfil'))
    )
    op.create_table('flc_permissao',
    sa.Column('seq_permissao', sa.Integer(), nullable=False),
    sa.Column('cod_permissao', sa.String(length=60), nullable=False),
    sa.Column('dsc_permissao', sa.String(length=255), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=True),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seq_permissao', name=op.f('pk_flc_permissao')),
    sa.UniqueConstraint('cod_permissao', name=op.f('uq_flc_permissao_cod_permissao'))
    )
    op.create_table('flc_perfil_permissao',
    sa.Column('seq_perfil_permissao', sa.Integer(), nullable=False),
    sa.Column('seq_perfil', sa.Integer(), nullable=False),
    sa.Column('seq_permissao', sa.Integer(), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['seq_perfil'], ['flc_perfil.seq_perfil'], name=op.f('fk_flc_perfil_permissao_seq_perfil_flc_perfil')),
    sa.ForeignKeyConstraint(['seq_permissao'], ['flc_permissao.seq_permissao'], name=op.f('fk_flc_perfil_permissao_seq_permissao_flc_permissao')),
    sa.PrimaryKeyConstraint('seq_perfil_permissao', name=op.f('pk_flc_perfil_permissao')),
    sa.UniqueConstraint('seq_perfil', 'seq_permissao', name='uq_perfil_permissao')
    )
    op.create_table('flc_usuario_perfil',
    sa.Column('seq_usuario_perfil', sa.Integer(), nullable=False),
    sa.Column('seq_usuario', sa.Integer(), nullable=False),
    sa.Column('seq_perfil', sa.Integer(), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['seq_perfil'], ['flc_perfil.seq_perfil'], name=op.f('fk_flc_usuario_perfil_seq_perfil_flc_perfil')),
    sa.ForeignKeyConstraint(['seq_usuario'], ['flc_usuario.seq_usuario'], name=op.f('fk_flc_usuario_perfil_seq_usuario_flc_usuario')),
    sa.PrimaryKeyConstraint('seq_usuario_perfil', name=op.f('pk_flc_usuario_perfil')),
    sa.UniqueConstraint('seq_usuario', 'seq_perfil', name='uq_usuario_perfil')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flc_usuario_perfil')
    op.drop_table('flc_perfil_permissao')
    op.drop_table('flc_permissao')
    op.drop_table('flc_perfil')
    # ### end Alembic commands ###
