"""saldo por fundo

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-12 10:51:11.442014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



VIEW_CALC = """
CREATE VIEW vw_flc_saldo_conta_fundo_calc AS
SELECT s.seq_saldo_conta_fundo,
       s.seq_conta,
       s.seq_fundo,
       s.dat_saldo,
       s.val_saldo,
       s.val_aplicacoes,
       s.val_resgates,
       s.seq_tipo_origem,
       s.seq_sistema_origem,
       COALESCE(LAG(s.val_saldo) OVER (
           PARTITION BY s.seq_conta, s.seq_fundo ORDER BY s.dat_saldo
       ), 0) AS val_saldo_inicial_derivado,
       s.val_saldo
         - COALESCE(LAG(s.val_saldo) OVER (
               PARTITION BY s.seq_conta, s.seq_fundo ORDER BY s.dat_saldo
           ), 0)
         - s.val_aplicacoes
         + s.val_resgates AS val_rendimento_calculado
FROM flc_saldo_conta_fundo s
WHERE s.ind_status = 'A'
"""

VIEW_AGREGADO = """
CREATE VIEW vw_flc_saldo_conta_agregado AS
SELECT s.seq_conta,
       s.dat_saldo,
       SUM(s.val_saldo) AS val_saldo,
       SUM(s.val_aplicacoes) AS val_aplicacoes,
       SUM(s.val_resgates) AS val_resgates,
       COUNT(*) AS qtd_fundos,
       CASE WHEN COUNT(DISTINCT t.txt_sigla || '|' || COALESCE(so.txt_sigla, '')) = 1
            THEN MIN(CASE t.txt_sigla
                       WHEN 'MANUAL' THEN 'Manual'
                       WHEN 'IMPORTADO' THEN 'Importado'
                       ELSE 'Automatizado - ' || COALESCE(so.txt_sigla, '')
                     END)
            ELSE 'Mista' END AS dsc_origem_consolidada
FROM flc_saldo_conta_fundo s
JOIN flc_tipo_origem_saldo t ON t.seq_tipo_origem_saldo = s.seq_tipo_origem
LEFT JOIN flc_sistema_origem so ON so.seq_sistema_origem = s.seq_sistema_origem
WHERE s.ind_status = 'A'
GROUP BY s.seq_conta, s.dat_saldo
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flc_sistema_origem',
    sa.Column('seq_sistema_origem', sa.Integer(), nullable=False),
    sa.Column('txt_sigla', sa.String(length=30), nullable=False),
    sa.Column('dsc_sistema_origem', sa.String(length=120), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=True),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seq_sistema_origem', name=op.f('pk_flc_sistema_origem')),
    sa.UniqueConstraint('txt_sigla', name=op.f('uq_flc_sistema_origem_txt_sigla'))
    )
    op.create_table('flc_tipo_origem_saldo',
    sa.Column('seq_tipo_origem_saldo', sa.Integer(), nullable=False),
    sa.Column('txt_sigla', sa.String(length=20), nullable=False),
    sa.Column('dsc_tipo_origem', sa.String(length=120), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=True),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seq_tipo_origem_saldo', name=op.f('pk_flc_tipo_origem_saldo')),
    sa.UniqueConstraint('txt_sigla', name=op.f('uq_flc_tipo_origem_saldo_txt_sigla'))
    )
    op.create_table('flc_fundo',
    sa.Column('seq_fundo', sa.Integer(), nullable=False),
    sa.Column('cod_fundo', sa.String(length=10), nullable=False),
    sa.Column('dsc_fundo', sa.String(length=120), nullable=True),
    sa.Column('seq_tipo_origem', sa.Integer(), nullable=False),
    sa.Column('seq_sistema_origem', sa.Integer(), nullable=True),
    sa.Column('ind_pendente_revisao', sa.String(length=1), nullable=False),
    sa.Column('dat_auto_cadastro', sa.Date(), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=True),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seq_sistema_origem'], ['flc_sistema_origem.seq_sistema_origem'], name=op.f('fk_flc_fundo_seq_sistema_origem_flc_sistema_origem')),
    sa.ForeignKeyConstraint(['seq_tipo_origem'], ['flc_tipo_origem_saldo.seq_tipo_origem_saldo'], name=op.f('fk_flc_fundo_seq_tipo_origem_flc_tipo_origem_saldo')),
    sa.PrimaryKeyConstraint('seq_fundo', name=op.f('pk_flc_fundo')),
    sa.UniqueConstraint('cod_fundo', name=op.f('uq_flc_fundo_cod_fundo'))
    )
    op.create_table('flc_saldo_conta_fundo',
    sa.Column('seq_saldo_conta_fundo', sa.Integer(), nullable=False),
    sa.Column('seq_conta', sa.Integer(), nullable=False),
    sa.Column('seq_fundo', sa.Integer(), nullable=False),
    sa.Column('dat_saldo', sa.Date(), nullable=False),
    sa.Column('val_saldo', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('val_aplicacoes', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('val_resgates', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('seq_tipo_origem', sa.Integer(), nullable=False),
    sa.Column('seq_sistema_origem', sa.Integer(), nullable=True),
    sa.Column('ind_status', sa.String(length=1), nullable=False),
    sa.Column('dat_inclusao', sa.Date(), nullable=False),
    sa.Column('cod_pessoa_inclusao', sa.Integer(), nullable=True),
    sa.Column('dat_alteracao', sa.Date(), nullable=True),
    sa.Column('cod_pessoa_alteracao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seq_conta'], ['flc_conta_bancaria.seq_conta'], name=op.f('fk_flc_saldo_conta_fundo_seq_conta_flc_conta_bancaria')),
    sa.ForeignKeyConstraint(['seq_fundo'], ['flc_fundo.seq_fundo'], name=op.f('fk_flc_saldo_conta_fundo_seq_fundo_flc_fundo')),
    sa.ForeignKeyConstraint(['seq_sistema_origem'], ['flc_sistema_origem.seq_sistema_origem'], name=op.f('fk_flc_saldo_conta_fundo_seq_sistema_origem_flc_sistema_origem')),
    sa.ForeignKeyConstraint(['seq_tipo_origem'], ['flc_tipo_origem_saldo.seq_tipo_origem_saldo'], name=op.f('fk_flc_saldo_conta_fundo_seq_tipo_origem_flc_tipo_origem_saldo')),
    sa.PrimaryKeyConstraint('seq_saldo_conta_fundo', name=op.f('pk_flc_saldo_conta_fundo'))
    )
    with op.batch_alter_table('flc_saldo_conta_fundo', schema=None) as batch_op:
        batch_op.create_index('ux_flc_saldo_conta_fundo_ativo', ['seq_conta', 'seq_fundo', 'dat_saldo'], unique=True, sqlite_where=sa.text("ind_status = 'A'"), postgresql_where=sa.text("ind_status = 'A'"))

    # ### end Alembic commands ###

    # Views de cálculo (decisão do produto — paridade com o Java; SQL portável)
    op.execute(VIEW_CALC)
    op.execute(VIEW_AGREGADO)


def downgrade() -> None:
    op.execute("DROP VIEW vw_flc_saldo_conta_agregado")
    op.execute("DROP VIEW vw_flc_saldo_conta_fundo_calc")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flc_saldo_conta_fundo', schema=None) as batch_op:
        batch_op.drop_index('ux_flc_saldo_conta_fundo_ativo', sqlite_where=sa.text("ind_status = 'A'"), postgresql_where=sa.text("ind_status = 'A'"))

    op.drop_table('flc_saldo_conta_fundo')
    op.drop_table('flc_fundo')
    op.drop_table('flc_tipo_origem_saldo')
    op.drop_table('flc_sistema_origem')
    # ### end Alembic commands ###
